const lol = {
  participants: {
    popupTitle: "Gente",
    title: "Participantes",
    subtitle: "Gente de dentro y de fuera de más de 20 países",
    profesores: {
      label: "Profesores",
      content: [
        "MARINA ARESPACOCHAGA",
        "JULIA VALLESPÍN",
        "JOSÉ MARÍA CANALEJAS",
        "MARGARITA ARIZA COPADO",
        "ÓSCAR JIMÉNEZ SALVADOR",
        "MARIAM RAMZI",
        "VÍCTOR GARCÍA BARBA",
        "ESTRELLA JUÁREZ",
        "GABRIEL MARTÍNEZ GARCÍA",
        "SONIA MARTÍNEZ",
        "JUAN ALCÓN",
        "ESTRELLA JUÁREZ",
        "PAULINO MARTÍN",
        "JOSE LUIS ADARME",
        "ISIDRO PEREA",
        "ALFONSO MAGAZ ROBAIN",
        "MIGUEL OCHANDO PÉREZ",
        "ADRIÁN CARRA",
        "LETICIA BALLESTER",
        "PILAR BLANCO",
        "JULIA OLIET",
      ],
    },
    alumnos: {
      label: "Profesores",
      content: [
        "BERNY UDISETH ALEMÁN ULLOA",
        "SAMANTHA ALVAREZ ARRANZ",
        "SARA ABABSEH MARTÍNEZ",
        "ISABEL APARICIO HENRIQUEZ DE LUNA",
        "BORJA ARRUFAT MAGALLARES",
        "NACHO ARRUFAT MAGALLARES",
        "MARÍA JESÚS BONAFONTE ALARIO",
        "JOSE COLLADO DÍAZ",
        "ALICIA CORONEL RUIZ",
        "ZAIRA CREMONA",
        "PALOMA DEL CUBO",
        "NORA DRIS MARCOS",
        "PATRICIA FERNÁDEZ GUTIÉRREZ",
        "BEATRIZ FERRERO CALVO",
        "NIEVES FRÍAS HUERTA",
        "ELENA GONZÁLEZ SÁNCHEZ",
        "INÉS LLASERA SAIZ",
        "JOEL MALAGON ESPINEL",
        "NEREA MANZANO SASIETA",
        "IRENE MÁRQUEZ FERNÁNDEZ",
        "SOFÍA MARTÍNEZ",
        "JUAN CARLOS MARTINEZ",
        "AITOR MARTÍNEZ",
        "FORTUNA MAYOR NEMOLATO",
        "ÁNGEL MÉNDEZ VELÁZQUEZ",
        "DAVID ORTEGA TORRES",
        "PABLO PANIAGUA MARTÍNEZ",
        "ALICIA PRIETO FERNÁNDEZ-QUERO",
        "MARIO RAMIREZ FERNANDEZ",
        "LUIS RUBIO MARTINEZ",
        "SANDRA SAN GREGORIO",
        "PALOMA SEOANE CIFRE",
        "TOMÁS SERAL",
        "PABLO SEVILLA",
        "VICTOR TERÁN RODRIGUEZ",
        "MARINA VICENTE GONZÁLEZ",
        "IRENE YAÑEZ",
        "ISABEL ARNAIZ DE LOS RÍOS",
        "ANA BLANCO DE LA FUENTE",
        "INÉS BRIZUELA REDONDO",
        "BEATRIZ BRUGAROLAS",
        "EUGENIA CRESPO VÁZQUEZ",
        "MARÍA DÁVALOS PRIETO",
        "RUBÉN DELGADO SACRISTÁN",
        "RAQUEL FERRERAS EXPÓSITO",
        "CARLOS FONT LEON",
        "DIEGO FUENTES RODRIGUEZ",
        "PETER GALKIN",
        "SERGIO GÓMEZ",
        "ROCÍO GONZÁLEZ JIMÉNEZ",
        "BEATRIZ GONZÁLEZ PLAZA",
        "IRENE HURTADO",
        "LAURA INGELMO NAVARRO",
        "EVA JIMÉNEZ DEL PINO",
        "RAQUEL MARTÍNEZ CRESPO",
        "DIEGO MOYANO RAMOS",
        "TELMO RICARDO NARVÁEZ GUERRA",
        "ARTURO ONGIL RODRÍGUEZ",
        "JAVIER PALACIOS CRUZ",
        "MARTA PEDREÑO AZNAR",
        "LUIS PÉREZ SOPEÑA",
        "PAULA RODRÍGUEZ ARENCIBIA",
        "ALBA RODRÍGUEZ PARIENTE",
        "ALICIA SANTIAGO ESTEBAN",
        "TOMÁS SERAL",
        "PABLO SEVILLA",
        "ESTEFANIA SEVILLA NARANJO",
        "MARTA MANCEÑIDO",
      ],
    },
    personalNoDocente: {
      label: "Personal no docente",
      content: ["EDUARDO GÁLVEZ", "JAVIER PIÑA", "ALBA PIÑA"],
    },
    deFuera: {
      recetasUrbanas: {
        label: "Recetas Urbanas",
        content: ["SANTIAGO CIRUGEDA", "ALICE ATTOUT", "JOSE BERBIELA BUSTAMANTE", "JUAN CARLOS MARTÍNEZ", "CAMERON BRAY", "MARTÍN CIANNI"],
      },
      alumnosProfesoresColectivos: {
        label: "Alumnos, profesores y colectivos…",
        content: [
          "ALBERTO BERNABÉ LACÁRCEL / ESPAÑA",
          "NIKLAS WUCHENAUER / ALEMANIA",
          "BIANCA WOISETSCHLÄGER ALEMANIA",
          "ANN KATHRIN GOLDECAMP ALEMANIA",
          "VALENTINO / AUSTRIA",
          "YING LI / CHINA",
          "ERIN LINSEY HUNT / EEUU",
          "JOSHUA AYLETT / EEUU–UK",
          "PABLO BARCELÓ MORENO / ESPAÑA",
          "DEIENE GONZÁLEZ URIARTE / ESPAÑA",
          "JAVIER DE LA MADRIZ / ESPAÑA",
          "MARTA LLORENS ECHEGARAY / ESPAÑA",
          "AISHATH GREEN / ESPAÑA",
          "JUAN GABRIEL PELEGRINA FERNÁNDEZ / ESPAÑA",
          "SERGIO / ESPAÑA",
          "IRENE / ESPAÑA",
          "ÁLVARO / ESPAÑA",
          "JORGE / ESPAÑA",
          "LLORESC BONET / ESPAÑA",
          "JOAQUÍN VILA / ESPAÑA",
          "JUAN JOSÉ ESTRADA / ESPAÑA",
          "ROBERTO PÉREZ / ESPAÑA",
          "JARA ROMERO ESCOLAR / ESPAÑA",
          "ALFONSO RAMIREZ MARCHENA / ESPAÑA",
          "JOSÉ ALEJO CABRERA RODRÍGUEZ / ESPAÑA",
          "KEVIN MARCO PACHECO / ESPAÑA",
          "EVA ALESANDRA CANDELA CASTAÑO / ESPAÑA",
          "VIRGINIA QUILEZ BERNABEU / ESPAÑA",
          "DUMAR SANTAMARÍA LLOPIS / ESPAÑA",
          "DAVID MARTÍNEZ TORRADO / ESPAÑA",
          "JAVIER SÁNCHEZ MERINA / ESPAÑA",
          "VIRGINE TERRARTIN / FRANCIA",
          "MARINE DELOUVRIER / FRANCIA",
          "LAETITIA HEDON / FRANCIA",
          "MÉGANE JOLIVEL / FRANCIA",
          "JOANA CAUWEL / FRANCIA",
          "JOANNY LEA / FRANCIA",
          "LUCAS ALEZRA / FRANCIA",
          "ISABELLE MOLLÉ / FRANCIA–FILIPINAS",
          "NATHALIE LAGARD / FRANCIA–RUSIA",
          "JOSHUA GRAN / UK",
          "GUILLERMO CORELLA / ESPAÑA",
          "PASCALE ATSMA / HOLANDA",
          "VALERIA PABIANO / ITALIA",
          "DAVIDE CALAPINTO / ITALIA",
          "ALESSAMOLTOZENA ZENA / ITALIA",
          "GALATEA VENTURELLI / ITALIA",
          "LIDIANA D’ONORIO / ITALIA",
          "MARINO MARIANNA / ITALIA",
          "JORGE LÓPEZ / ESPAÑA",
          "KANG-JUN NG / MALAYSIA",
          "ALINI HALIM / MALAYSIA",
          "NAZMI SAMLUN / MALAYSIA",
          "EUSEBIO BAÑUELOU GONZÁLEZ / MÉXICO",
          "DOROTA ADAMMCZYIC / POLONIA",
          "MARTA MOCHNIAK / POLONIA",
          "YASMINE SABBAH / LÍBANO",
          "NADINE KABBAN / LÍBANO–CANADÁ",
          "ANDREEA-DIANA DRAGNESCU / RUMANÍA",
          "BOB MORARD / SUIZA",
          "ALEXANDRE GUTIÉRREZ / SUIZA",
          "WILLIAM CHAMI / SUIZA–EEUU–LÍBANO",
          "IKBAL CICEK / TURQUÍA",
          "EGE BALCIL / TURQUÍA",
          "JAMES SIDAWAY / UK",
          "DAFYDD JONES-DAVIES / UK",
          "ARI ARGALIOGIO / UK",
          "BRYAN BRAOROOK / UK",
          "DANIEL BIANCHI / UK",
          "CHRIS JONES / UK",
          "ANDREW DAWSON / UK/–AUSTRALIA",
          "TROIANI IGEA / UK–AUSTRALIA",
          "ALICIA SARDI / VENEZUELA",
          "FLAVIA GARCÍA / ITALIA",
          "SIRO SANTOS GARCÍA / ESPAÑA",
          "ANTONIO BOVERO / ITALIA",
          "ERANNAN BENT / IRLANDA–FINLANDIA",
          "JUAN GABRIEL PELEGRINA / ESPAÑA",
          "JAVIER TONDA / ESPAÑA",
        ],
      },
    },
  },
};

module.exports = {
  lol,
};
